### ISSUE TITLE
Testing UI with API for service calls and displaying output to UI

### ISSUE THREAD

**Issue by Manuja-B** [airavata-courses/DevoTeam#14]
Test the following happy path scenarios:

1. When user inputs year, date, month, day, radar values and hits result; user should receive "Sent user input to micro-services" 

2. When user inputs year, date, month, day, radar values and hits result; user should receive "Request in process please wait" if key is present in redis cache.

3. When user inputs year, date, month, day, radar values and hits result; user interface should receive reflectivity image plot in base64 format and maximum spectrum width value to be parsed by UI component and displayed accordingly.

**Comment by Manuja-B** [comment]
- Implemented modular testing by running services independently using request calls from postman 

 to API and verifying output of each micro service and API in accordance with above mentioned test cases.

- Implemented end to end testing upon integration of services and UI.

- Issues: 
. web app would hit a post request on refresh and when clicking result(Resolved edf17642ec111cdc087f1880bd5078e10a780d67). 

- Updates:
. web app should display message progress like in process or message sent for processing.

**Comment by Invictus17** [comment]
- Output visible for valid user input and happy path scenarios.

- Sessions visible with timestamps.

Closing this issue for milestone 1
