### ISSUE TITLE
[DEPLOYMENT] Issues in deployment

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/DevoTeam#25]
Hi team,

1. Please update instructions for installing in Ubuntu 18.04, I don't have any other system.
2. Your microservice should not need eclipse to start, simple mvn clean install && mvn spring-boot:run should start it.
3. Your DB should not require mysql work bench to initialize default tables, provide an sql script that I can run.

Please get back to me as soon as you fix these issues (preferably today afternoon).

**Comment by Invictus17** [comment]
Hi KalaRaja,
Working on this immediately.

**Comment by Manuja-B** [comment]
Updating the readme.

**Comment by Invictus17** [comment]
Updated README_Linux.md in all branches

- Waiting for an update on issue: #26

**Comment by KalaRaja** [comment]
the user management microservice does not start, gives me sql connection error 
![Screen Shot 2020-02-26 at 6 02 11 PM](https://user-images.githubusercontent.com/42894144/75396553-c9c12700-58c2-11ea-9793-b671be985bf5.png)

note that i have used the same username and password of my sql in the application.properties

the UI on 'npm start' after 'npm install' gives me following error:
![Screen Shot 2020-02-26 at 6 14 39 PM](https://user-images.githubusercontent.com/42894144/75397051-f32e8280-58c3-11ea-828f-910182222986.png)

**Comment by KalaRaja** [comment]
also, you MUST provide commands in the markdown/Wiki to stop 3rd party services, like redis, rabbitmq and mysql.

**Comment by Manuja-B** [comment]
Fixed the bug : Find latest Readme for linux under Master branch
