### ISSUE TITLE
Test User Management service in Linux

### ISSUE THREAD

**Issue by Invictus17** [airavata-courses/DevoTeam#26]
Hi @Manuja-B ,

While testing the User management module in Linux I found the following error:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.865 s
[INFO] Finished at: 2020-02-25T02:33:39-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.6.RELEASE:run (default-cli) on project UserManagement: An exception occurred while running. null: InvocationTargetException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

- Follow the steps mentioned in README_Linux.md to get it started. 

- I suspect there could be some error connecting to the Mysql DB. I have checked the ports and username, password.

- Update issue :  #25 after handling this.

**Comment by Manuja-B** [comment]
Please add the following dependency in pom.xml if you are using Java 9
<dependency>
        <groupId>javax.xml.bind</groupId>
        <artifactId>jaxb-api</artifactId>
        <version>2.3.0</version>
</dependency>

Also please try adding following dependency
<dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-entitymanager</artifactId>
    <version>5.2.3.Final</version>
</dependency>

**Comment by Invictus17** [comment]
Hi @Manuja-B ,
Please make the necessary commits to the branches for updating pom.xml or suggest installing a specific java version in the readme.

**Comment by Manuja-B** [comment]
Editted the pom.xml

**Comment by Invictus17** [comment]
Hi @Manuja-B please check issue #25 for latest error in Linux for User management service

**Comment by Manuja-B** [comment]
pom.xml file for user management service updated
Commit: 7ddeaa85f4b5c85bd8eeab59fc1643525f48400d
