### ISSUE TITLE
Message Broker Design

### ISSUE THREAD

**Issue by Manuja-B** [airavata-courses/DevoTeam#3]
To Design and develop a Message broker for the Distributed System

**Comment by Invictus17** [comment]
- Validated basic message broker diagram with the Professors for Assignment 1.

**Issue realised:** Services were tightly coupled. Need to separate them with an orchestrator like Consul.

**Comment by Invictus17** [comment]
For Assignment 1 a RabbitMQ message broker design has been implemented and tested for communication between the micro-services.
![Message_broker_Assignment 1](https://user-images.githubusercontent.com/34004948/74306995-33bdc600-4d32-11ea-9c12-ba5b3a2b0717.jpg)
