### ISSUE TITLE
Test docker compose for API, Data Ingestion, Model Execution, Post processing

### ISSUE THREAD

**Issue by Invictus17** [airavata-courses/DevoTeam#33]
Test if curl hit to API validates the following journeys:

1. Creates a key store in redis for new input and publishes to rabbitmq.
2. Data Ingestion -> Model Execution & Post processing functionality works to produce reflectivity byte array and maximum spectrum width value.
3. Data Ingestion, Model Execution & Post processing are able to publish to rabbitmq.
4. Data Ingestion, Model Execution & Post processing are able to subscribe from rabbitmq.
5. redis has latest key value results of reflectivity byte 64 array and maximum spectrum width value.

**Comment by Invictus17** [comment]
Validated all the journeys mentioned above using a dummy curl hit:
Opened a terminal in Linux and hit:  
curl --header "Content-Type: application/json" --request POST --data '{"email":"yolo","year":"2019","month":"02","day":"09","radar":"KIND","t_id":"wdaw2"}' http://localhost:8081/weather

**Comment by Manuja-B** [comment]
curl --header "Content-Type: application/json" --request POST --data '{"email":"yolo","password":"S","firstName":"yt","lastName":"xx", "contactNumber":"123"}' http://localhost:8082/signUp
