### ISSUE TITLE
Jmeter testing : Would need information on the data format.

### ISSUE THREAD

**Issue by AsimAzmi** [airavata-courses/DevoTeam#56]
You can share the json data format required to hit the API Gateway for load testing. 
Also, you may share the internal Rest Path for the  API Gateway so that user can bypass the login process and hit the URL directly.

**Comment by Invictus17** [comment]
Hi,

endpoint ip: http://149.165.169.244:30000/weather

JSON body:
{"email":"abc@gmail.com", "year":"2019", "month":"04", "day":"02","radar":"KIND", "t_id":"wdadaawrw"}
