### ISSUE TITLE
Jmeter testing on system deployed with istio

### ISSUE THREAD

**Issue by Invictus17** [airavata-courses/DevoTeam#66]
Test the system deployed with replica 1 and 3 to find it's breaking point.

**Comment by sainathpv** [comment]
The system has been load tested using Apache Jmeter for 1000 and 3000 requests using replicas 1 and 3 and the corresponding graphs and aggregate data have been generated.

**Comment by Invictus17** [comment]
As observed we got better results compared to our previous system version without a mesh configured with it Initially:
- For replica == 1 the system breaks at around 800-900 users with some of the requests being lost. Error around 9%. (https://github.com/airavata-courses/DevoTeam/issues/51)
- For replica == 1 the system now breaks at around 1300-1400 users.
- Results for replica ==2 & 3 were similar to our initial system and we belive implementing the system with clusters of redis and rabbitmq would improve the robustness of the system
